baseURL = "/"
languageCode = "en-us"
title = "Travessel"
theme="restaurant-hugo"
summaryLength = "7"



# Menu
[menu]
	
	[[menu.nav]]
    name = "Home"
    URL = "hero-area"
    weight = 1

    [[menu.nav]]
    name = "Inbound Travelling"
    URL = "inbound"
    weight = 2

    [[menu.nav]]
    name = "Outbound Travelling"
    URL = "outbound"
    weight = 3

    [[menu.nav]]
    name = "Hotels"
    URL = "hotel"
    weight = 4

    [[menu.nav]]
    name = "Transport"
    URL = "transportation"
    weight = 5

    [[menu.nav]]
    name = "Inbound Entertainment"
    URL = "entertainment"
    weight = 5

    [[menu.nav]]
    name = "Subscribe"
    URL = "subscribe"
    weight = 6



# Global Settings
[params]
logo = "images/logo.png"


[params.heroArea]
enable = true
[params.heroImg ] 
url =  "images/header.jpg" 


#gallery item

[params.gallery]
enable = true
title= "Featured <span>Tour Packages</span>"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-2.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-3.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-4.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-2.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-3.jpg"


[params.about]
enable = true
title= "<span>Travessel</span>"
bgImage = "images/logo.png"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in </br>voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat Ut enim ad minim veniam"




#food Menu

[params.foodMenu]
enable = false
title = "Our Easy <span>PRICE</span>"
description= " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco"
subtitle = "FEATURED ON THE WEEK"

[[params.foodMenu.item]]
title="Pancakes n' Such Titas"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 125.00"

[[params.foodMenu.item]]
title="Caesar Salad"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 100.00"

[[params.foodMenu.item]]
title="Steak with a Garlic and Parsley Risotto"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 20.00"

[[params.foodMenu.item]]
title="Meat of Skewers"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 45.00"

[[params.foodMenu.item]]
title="Pancakes n' Such"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 25.00"



#subscription

[params.subscription]
enable = true
title= "SUBSCRIBE to our <span>NEWSLETTER</span>"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"

#Mailchimp subscription configaration 
formAction = "https://charles.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e"
formName = "b_f95ece2732a6e9925f2e70a61_b1e227529e"

#Contact 

[params.contact]
enable = true
title= "our <span> Contact Us </span>"
subtitle= "SIGN UP FOR EMAIL ALERTS"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"


#Footer 

[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>Tour Packages</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "+62 853 5538 0557"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "Orchard Park Blk B No.7, Agung Podomoro Land, Batam Centre, 29432, Batam, Indonesia"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "travessel.id@gmail.com"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/travessel/"


[[params.footer.socialLink]]
icon = "whatsapp"
link = "https://api.whatsapp.com/send?phone=6285355380557&text=Halo%20Travessel,%20saya%20mau%20tanya"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/travessel/"


#Footer Copyright

#Footer Copyright Text
[params.footerCopyright]
enable = true
Text = "Copyright 2019 - All Rights Reserved.Design and Developed By charleskya"




#blog 
[params.blog]
enable = true
title = "Latest <span>Tour Packages</span>"









