backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "hotel" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Hotel" # Used in the UI, ie.: "New Post"
    folder: "site/content/hotel" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nama Hotel", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "gambar", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "inbound" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Inbound" # Used in the UI, ie.: "New Post"
    folder: "site/content/inbound" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nama", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "gambar", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "outbound" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Outbound" # Used in the UI, ie.: "New Post"
    folder: "site/content/outbound" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nama Hotel", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "gambar", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "transportation" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Transportation" # Used in the UI, ie.: "New Post"
    folder: "site/content/transportation" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nama", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "gambar", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "entertainment" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Entertainment" # Used in the UI, ie.: "New Post"
    folder: "site/content/entertainment" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nama", name: "name", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "gambar", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}